In [1]:
#https://simplywall.st/stocks/bd/market-cap-large
import pandas as pd
import numpy as np
import re

In [2]:
df=pd.read_excel('C:\\Users\\nafissaad\\\Desktop\\Sector.xlsx')
df

,Company,Last Price,7D Return,1Y Return,Market Cap,Analysts Target,Valuation,Growth,Div Yield,Industry,Unnamed: 10
0,NaN,GPGrameenphone,৳286.60,0.000,-0.015,৳387.0b,৳345.75,PE13x,S6.3%,0.066,Telecom
1,NaN,WALTONHILWalton Hi-Tech Industries,"৳1,047.70",0.000,-0.028,৳317.4b,NaN,PE49.1x,NaN,0.024,Consumer Durables
2,NaN,BATBCBritish American Tobacco Bangladesh,৳518.70,0.000,-0.039,৳280.1b,৳577.00,PE15.3x,E11.9%,0.039,"Food, Beverage & Tobacco"
3,NaN,SQURPHARMASquare Pharmaceuticals,৳209.80,0.000,-0.023,৳186.0b,৳337.67,PE9.9x,E12.0%,0.048,Pharmaceuticals & Biotech
4,NaN,ROBIRobi Axiata,৳30.00,0.000,-0.191,৳157.1b,NaN,PE85x,NaN,0.023,Telecom
...,...,...,...,...,...,...,...,...,...,...,...
211,NaN,ADVENTAdvent Pharma,৳26.70,0.011,0.060,৳2.5b,NaN,PE25.3x,NaN,0.007,Pharmaceuticals & Biotech
212,NaN,SILCOPHLSilco Pharmaceuticals,৳24.20,-0.008,-0.087,৳2.5b,NaN,PE36.7x,NaN,0.021,Pharmaceuticals & Biotech
213,NaN,BDLAMPSBangladesh Lamps,৳252.20,0.000,0.017,৳2.5b,NaN,PE69.8x,NaN,0.007,Capital Goods
214,NaN,GHCLGlobal Heavy Chemicals,৳35.10,0.000,-0.011,৳2.5b,NaN,PS5.4x,NaN,0.006,Materials
215,NaN,PRIMELIFEPrime Islami Life Insurance,৳79.20,-0.014,0.349,৳2.5b,NaN,PB13.9x,NaN,0.003,Insurance

In [3]:
len(df.columns)

11

In [4]:
df.rename(columns = {df.columns[0]:df.columns[-1],df.columns[1]:df.columns[0], df.columns[2]:df.columns[1],
                              df.columns[3]:df.columns[2],df.columns[4]:df.columns[3],df.columns[5]:df.columns[4],
                              df.columns[6]:df.columns[5],df.columns[7]:df.columns[6],
                     df.columns[8]:df.columns[7],df.columns[9]:df.columns[8],
                    df.columns[10]:df.columns[9]}, inplace = True)
df

,Unnamed: 10,Company,Last Price,7D Return,1Y Return,Market Cap,Analysts Target,Valuation,Growth,Div Yield,Industry
0,NaN,GPGrameenphone,৳286.60,0.000,-0.015,৳387.0b,৳345.75,PE13x,S6.3%,0.066,Telecom
1,NaN,WALTONHILWalton Hi-Tech Industries,"৳1,047.70",0.000,-0.028,৳317.4b,NaN,PE49.1x,NaN,0.024,Consumer Durables
2,NaN,BATBCBritish American Tobacco Bangladesh,৳518.70,0.000,-0.039,৳280.1b,৳577.00,PE15.3x,E11.9%,0.039,"Food, Beverage & Tobacco"
3,NaN,SQURPHARMASquare Pharmaceuticals,৳209.80,0.000,-0.023,৳186.0b,৳337.67,PE9.9x,E12.0%,0.048,Pharmaceuticals & Biotech
4,NaN,ROBIRobi Axiata,৳30.00,0.000,-0.191,৳157.1b,NaN,PE85x,NaN,0.023,Telecom
...,...,...,...,...,...,...,...,...,...,...,...
211,NaN,ADVENTAdvent Pharma,৳26.70,0.011,0.060,৳2.5b,NaN,PE25.3x,NaN,0.007,Pharmaceuticals & Biotech
212,NaN,SILCOPHLSilco Pharmaceuticals,৳24.20,-0.008,-0.087,৳2.5b,NaN,PE36.7x,NaN,0.021,Pharmaceuticals & Biotech
213,NaN,BDLAMPSBangladesh Lamps,৳252.20,0.000,0.017,৳2.5b,NaN,PE69.8x,NaN,0.007,Capital Goods
214,NaN,GHCLGlobal Heavy Chemicals,৳35.10,0.000,-0.011,৳2.5b,NaN,PS5.4x,NaN,0.006,Materials
215,NaN,PRIMELIFEPrime Islami Life Insurance,৳79.20,-0.014,0.349,৳2.5b,NaN,PB13.9x,NaN,0.003,Insurance

In [5]:
df

,Unnamed: 10,Company,Last Price,7D Return,1Y Return,Market Cap,Analysts Target,Valuation,Growth,Div Yield,Industry
0,NaN,GPGrameenphone,৳286.60,0.000,-0.015,৳387.0b,৳345.75,PE13x,S6.3%,0.066,Telecom
1,NaN,WALTONHILWalton Hi-Tech Industries,"৳1,047.70",0.000,-0.028,৳317.4b,NaN,PE49.1x,NaN,0.024,Consumer Durables
2,NaN,BATBCBritish American Tobacco Bangladesh,৳518.70,0.000,-0.039,৳280.1b,৳577.00,PE15.3x,E11.9%,0.039,"Food, Beverage & Tobacco"
3,NaN,SQURPHARMASquare Pharmaceuticals,৳209.80,0.000,-0.023,৳186.0b,৳337.67,PE9.9x,E12.0%,0.048,Pharmaceuticals & Biotech
4,NaN,ROBIRobi Axiata,৳30.00,0.000,-0.191,৳157.1b,NaN,PE85x,NaN,0.023,Telecom
...,...,...,...,...,...,...,...,...,...,...,...
211,NaN,ADVENTAdvent Pharma,৳26.70,0.011,0.060,৳2.5b,NaN,PE25.3x,NaN,0.007,Pharmaceuticals & Biotech
212,NaN,SILCOPHLSilco Pharmaceuticals,৳24.20,-0.008,-0.087,৳2.5b,NaN,PE36.7x,NaN,0.021,Pharmaceuticals & Biotech
213,NaN,BDLAMPSBangladesh Lamps,৳252.20,0.000,0.017,৳2.5b,NaN,PE69.8x,NaN,0.007,Capital Goods
214,NaN,GHCLGlobal Heavy Chemicals,৳35.10,0.000,-0.011,৳2.5b,NaN,PS5.4x,NaN,0.006,Materials
215,NaN,PRIMELIFEPrime Islami Life Insurance,৳79.20,-0.014,0.349,৳2.5b,NaN,PB13.9x,NaN,0.003,Insurance

In [6]:
df=df.drop(df.columns[0],axis=1)
df

,Company,Last Price,7D Return,1Y Return,Market Cap,Analysts Target,Valuation,Growth,Div Yield,Industry
0,GPGrameenphone,৳286.60,0.000,-0.015,৳387.0b,৳345.75,PE13x,S6.3%,0.066,Telecom
1,WALTONHILWalton Hi-Tech Industries,"৳1,047.70",0.000,-0.028,৳317.4b,NaN,PE49.1x,NaN,0.024,Consumer Durables
2,BATBCBritish American Tobacco Bangladesh,৳518.70,0.000,-0.039,৳280.1b,৳577.00,PE15.3x,E11.9%,0.039,"Food, Beverage & Tobacco"
3,SQURPHARMASquare Pharmaceuticals,৳209.80,0.000,-0.023,৳186.0b,৳337.67,PE9.9x,E12.0%,0.048,Pharmaceuticals & Biotech
4,ROBIRobi Axiata,৳30.00,0.000,-0.191,৳157.1b,NaN,PE85x,NaN,0.023,Telecom
...,...,...,...,...,...,...,...,...,...,...
211,ADVENTAdvent Pharma,৳26.70,0.011,0.060,৳2.5b,NaN,PE25.3x,NaN,0.007,Pharmaceuticals & Biotech
212,SILCOPHLSilco Pharmaceuticals,৳24.20,-0.008,-0.087,৳2.5b,NaN,PE36.7x,NaN,0.021,Pharmaceuticals & Biotech
213,BDLAMPSBangladesh Lamps,৳252.20,0.000,0.017,৳2.5b,NaN,PE69.8x,NaN,0.007,Capital Goods
214,GHCLGlobal Heavy Chemicals,৳35.10,0.000,-0.011,৳2.5b,NaN,PS5.4x,NaN,0.006,Materials
215,PRIMELIFEPrime Islami Life Insurance,৳79.20,-0.014,0.349,৳2.5b,NaN,PB13.9x,NaN,0.003,Insurance

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          216 non-null    object
 1   Last Price       216 non-null    object
 2   7D Return        216 non-null    float64
 3   1Y Return        211 non-null    float64
 4   Market Cap       216 non-null    object
 5   Analysts Target  21 non-null     object
 6   Valuation        201 non-null    object
 7   Growth           16 non-null     object
 8   Div Yield        207 non-null    float64
 9   Industry         216 non-null    object
dtypes: float64(3), object(7)
memory usage: 17.0+ KB

In [8]:
for i in df.index:
    x=re.sub(",",'',df.loc[i,'Last Price'])
    df.loc[i,'Last Price']=re.findall("\d+\.\d+",x)[0]
    x2=re.sub(",",'',df.loc[i,'Market Cap'])
    df.loc[i,'Market Cap']=re.findall("\d+\.\d+",x2)[0]

In [9]:
df

,Company,Last Price,7D Return,1Y Return,Market Cap,Analysts Target,Valuation,Growth,Div Yield,Industry
0,GPGrameenphone,286.60,0.000,-0.015,387.0,৳345.75,PE13x,S6.3%,0.066,Telecom
1,WALTONHILWalton Hi-Tech Industries,1047.70,0.000,-0.028,317.4,NaN,PE49.1x,NaN,0.024,Consumer Durables
2,BATBCBritish American Tobacco Bangladesh,518.70,0.000,-0.039,280.1,৳577.00,PE15.3x,E11.9%,0.039,"Food, Beverage & Tobacco"
3,SQURPHARMASquare Pharmaceuticals,209.80,0.000,-0.023,186.0,৳337.67,PE9.9x,E12.0%,0.048,Pharmaceuticals & Biotech
4,ROBIRobi Axiata,30.00,0.000,-0.191,157.1,NaN,PE85x,NaN,0.023,Telecom
...,...,...,...,...,...,...,...,...,...,...
211,ADVENTAdvent Pharma,26.70,0.011,0.060,2.5,NaN,PE25.3x,NaN,0.007,Pharmaceuticals & Biotech
212,SILCOPHLSilco Pharmaceuticals,24.20,-0.008,-0.087,2.5,NaN,PE36.7x,NaN,0.021,Pharmaceuticals & Biotech
213,BDLAMPSBangladesh Lamps,252.20,0.000,0.017,2.5,NaN,PE69.8x,NaN,0.007,Capital Goods
214,GHCLGlobal Heavy Chemicals,35.10,0.000,-0.011,2.5,NaN,PS5.4x,NaN,0.006,Materials
215,PRIMELIFEPrime Islami Life Insurance,79.20,-0.014,0.349,2.5,NaN,PB13.9x,NaN,0.003,Insurance

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          216 non-null    object
 1   Last Price       216 non-null    object
 2   7D Return        216 non-null    float64
 3   1Y Return        211 non-null    float64
 4   Market Cap       216 non-null    object
 5   Analysts Target  21 non-null     object
 6   Valuation        201 non-null    object
 7   Growth           16 non-null     object
 8   Div Yield        207 non-null    float64
 9   Industry         216 non-null    object
dtypes: float64(3), object(7)
memory usage: 17.0+ KB

In [11]:
df['Last Price']=df['Last Price'].astype('float')
df['Market Cap']=df['Market Cap'].astype('float')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          216 non-null    object
 1   Last Price       216 non-null    float64
 2   7D Return        216 non-null    float64
 3   1Y Return        211 non-null    float64
 4   Market Cap       216 non-null    float64
 5   Analysts Target  21 non-null     object
 6   Valuation        201 non-null    object
 7   Growth           16 non-null     object
 8   Div Yield        207 non-null    float64
 9   Industry         216 non-null    object
dtypes: float64(5), object(5)
memory usage: 17.0+ KB

In [13]:
df['Industry'].value_counts()

Consumer Durables                         36
Banks                                     35
Materials                                 26
Insurance                                 20
Diversified Financials                    15
Food, Beverage & Tobacco                  14
Pharmaceuticals & Biotech                 13
Capital Goods                             13
Utilities                                  9
Energy                                     8
Telecom                                    5
Household                                  4
Consumer Services                          3
Automobiles                                3
Transportation                             2
Retail                                     2
Commercial Services                        2
Healthcare                                 2
Software                                   2
Real Estate Management and Development     1
Tech                                       1
Name: Industry, dtype: int64

In [14]:
df['Industry'].unique()

array(['Telecom', 'Consumer Durables', 'Food, Beverage & Tobacco',
       'Pharmaceuticals & Biotech', 'Utilities', 'Capital Goods',
       'Materials', 'Household', 'Diversified Financials', 'Banks',
       'Energy', 'Consumer Services', 'Insurance', 'Transportation',
       'Retail', 'Commercial Services', 'Healthcare', 'Software',
       'Real Estate Management and Development', 'Automobiles', 'Tech'],
      dtype=object)

In [15]:
x=df[df.Industry=='Telecom']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.4

In [16]:
x=df[df.Industry=='Banks']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.02857142857142857

In [17]:
x=df[df.Industry=='Materials']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.19230769230769232

In [18]:
x=df[df.Industry=='Insurance']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.45

In [19]:
x=df[df.Industry=='Diversified Financials']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.06666666666666667

In [20]:
x=df[df.Industry=='Food, Beverage & Tobacco']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.35714285714285715

In [21]:
x=df[df.Industry=='Pharmaceuticals & Biotech']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.07692307692307693

In [22]:
x=df[df.Industry=='Capital Goods']['1Y Return']>=0.10
x.value_counts()[1]/x.value_counts().sum()

0.07692307692307693

In [25]:
x=df[df.Industry=='Utilities']['1Y Return']>=0.10
x.value_counts()

False    9
Name: 1Y Return, dtype: int64