In [117]:
import pandas as pd
from binance.client import Client
import numpy as np
client=Client()

In [118]:
def getdata(symbol,start):
    frame=pd.DataFrame(client.get_historical_klines(symbol,'1h',start))
    frame=frame.iloc[:,:6]
    frame.columns=['Time','Open','High','Low','Close','Volume']
    frame.set_index('Time',inplace=True)
    frame.index=pd.to_datetime(frame.index,unit='ms')
    frame=frame.astype(float)
    return frame

In [119]:
df=getdata('BTCUSDT','2020-01-01')
df

                          Open       High        Low      Close       Volume
Time
2020-01-01 00:00:00    7195.24    7196.25    7175.46    7177.02   511.814901
2020-01-01 01:00:00    7176.47    7230.00    7175.71    7216.27   883.052603
2020-01-01 02:00:00    7215.52    7244.87    7211.41    7242.85   655.156809
2020-01-01 03:00:00    7242.66    7245.00    7220.00    7225.01   783.724867
2020-01-01 04:00:00    7225.00    7230.00    7215.03    7217.27   467.812578
...                        ...        ...        ...        ...          ...
2025-07-27 12:00:00  118072.71  118111.34  117890.00  118097.39   298.944250
2025-07-27 13:00:00  118097.39  118217.60  118085.87  118201.99   217.843110
2025-07-27 14:00:00  118201.99  118499.00  118149.96  118422.16   467.709230
2025-07-27 15:00:00  118422.16  118588.00  118236.84  118585.74   601.555060
2025-07-27 16:00:00  118585.75  119530.00  118585.75  119519.99  1742.596320

[48801 rows x 5 columns]

In [120]:
df['chg']=np.log(df.Close.pct_change()+1)
df

,Open,High,Low,Close,Volume,chg
Time,,,,,,
2020-01-01 00:00:00,7195.24,7196.25,7175.46,7177.02,511.814901,NaN
2020-01-01 01:00:00,7176.47,7230.00,7175.71,7216.27,883.052603,0.005454
2020-01-01 02:00:00,7215.52,7244.87,7211.41,7242.85,655.156809,0.003677
2020-01-01 03:00:00,7242.66,7245.00,7220.00,7225.01,783.724867,-0.002466
2020-01-01 04:00:00,7225.00,7230.00,7215.03,7217.27,467.812578,-0.001072
...,...,...,...,...,...,...
2025-07-27 12:00:00,118072.71,118111.34,117890.00,118097.39,298.944250,0.000209
2025-07-27 13:00:00,118097.39,118217.60,118085.87,118201.99,217.843110,0.000885
2025-07-27 14:00:00,118201.99,118499.00,118149.96,118422.16,467.709230,0.001861
2025-07-27 15:00:00,118422.16,118588.00,118236.84,118585.74,601.555060,0.001380
2025-07-27 16:00:00,118585.75,119530.00,118585.75,119519.99,1742.596320,0.007847

In [121]:
df['12h_chg']=df.chg.rolling(12).sum()
df

,Open,High,Low,Close,Volume,chg,12h_chg
Time,,,,,,,
2020-01-01 00:00:00,7195.24,7196.25,7175.46,7177.02,511.814901,NaN,NaN
2020-01-01 01:00:00,7176.47,7230.00,7175.71,7216.27,883.052603,0.005454,NaN
2020-01-01 02:00:00,7215.52,7244.87,7211.41,7242.85,655.156809,0.003677,NaN
2020-01-01 03:00:00,7242.66,7245.00,7220.00,7225.01,783.724867,-0.002466,NaN
2020-01-01 04:00:00,7225.00,7230.00,7215.03,7217.27,467.812578,-0.001072,NaN
...,...,...,...,...,...,...,...
2025-07-27 12:00:00,118072.71,118111.34,117890.00,118097.39,298.944250,0.000209,0.001232
2025-07-27 13:00:00,118097.39,118217.60,118085.87,118201.99,217.843110,0.000885,0.000846
2025-07-27 14:00:00,118201.99,118499.00,118149.96,118422.16,467.709230,0.001861,0.000948
2025-07-27 15:00:00,118422.16,118588.00,118236.84,118585.74,601.555060,0.001380,0.003403
2025-07-27 16:00:00,118585.75,119530.00,118585.75,119519.99,1742.596320,0.007847,0.010978

In [122]:
df.dropna(inplace=True)

In [123]:
df

,Open,High,Low,Close,Volume,chg,12h_chg
Time,,,,,,,
2020-01-01 12:00:00,7197.20,7233.33,7196.15,7225.59,868.753580,0.003937,0.006745
2020-01-01 13:00:00,7225.84,7231.89,7212.88,7221.20,612.180902,-0.000608,0.000683
2020-01-01 14:00:00,7221.17,7234.97,7208.17,7221.43,617.714185,0.000032,-0.002962
2020-01-01 15:00:00,7221.60,7255.00,7218.29,7234.19,1393.888792,0.001765,0.001270
2020-01-01 16:00:00,7234.20,7246.42,7214.00,7245.37,881.932780,0.001544,0.003886
...,...,...,...,...,...,...,...
2025-07-27 12:00:00,118072.71,118111.34,117890.00,118097.39,298.944250,0.000209,0.001232
2025-07-27 13:00:00,118097.39,118217.60,118085.87,118201.99,217.843110,0.000885,0.000846
2025-07-27 14:00:00,118201.99,118499.00,118149.96,118422.16,467.709230,0.001861,0.000948
2025-07-27 15:00:00,118422.16,118588.00,118236.84,118585.74,601.555060,0.001380,0.003403
2025-07-27 16:00:00,118585.75,119530.00,118585.75,119519.99,1742.596320,0.007847,0.010978

In [124]:
df['buyprice']=df.Open.shift(-1)
df

,Open,High,Low,Close,Volume,chg,12h_chg,buyprice
Time,,,,,,,,
2020-01-01 12:00:00,7197.20,7233.33,7196.15,7225.59,868.753580,0.003937,0.006745,7225.84
2020-01-01 13:00:00,7225.84,7231.89,7212.88,7221.20,612.180902,-0.000608,0.000683,7221.17
2020-01-01 14:00:00,7221.17,7234.97,7208.17,7221.43,617.714185,0.000032,-0.002962,7221.60
2020-01-01 15:00:00,7221.60,7255.00,7218.29,7234.19,1393.888792,0.001765,0.001270,7234.20
2020-01-01 16:00:00,7234.20,7246.42,7214.00,7245.37,881.932780,0.001544,0.003886,7244.34
...,...,...,...,...,...,...,...,...
2025-07-27 12:00:00,118072.71,118111.34,117890.00,118097.39,298.944250,0.000209,0.001232,118097.39
2025-07-27 13:00:00,118097.39,118217.60,118085.87,118201.99,217.843110,0.000885,0.000846,118201.99
2025-07-27 14:00:00,118201.99,118499.00,118149.96,118422.16,467.709230,0.001861,0.000948,118422.16
2025-07-27 15:00:00,118422.16,118588.00,118236.84,118585.74,601.555060,0.001380,0.003403,118585.75
2025-07-27 16:00:00,118585.75,119530.00,118585.75,119519.99,1742.596320,0.007847,0.010978,NaN

In [125]:
df

,Open,High,Low,Close,Volume,chg,12h_chg,buyprice
Time,,,,,,,,
2020-01-01 12:00:00,7197.20,7233.33,7196.15,7225.59,868.753580,0.003937,0.006745,7225.84
2020-01-01 13:00:00,7225.84,7231.89,7212.88,7221.20,612.180902,-0.000608,0.000683,7221.17
2020-01-01 14:00:00,7221.17,7234.97,7208.17,7221.43,617.714185,0.000032,-0.002962,7221.60
2020-01-01 15:00:00,7221.60,7255.00,7218.29,7234.19,1393.888792,0.001765,0.001270,7234.20
2020-01-01 16:00:00,7234.20,7246.42,7214.00,7245.37,881.932780,0.001544,0.003886,7244.34
...,...,...,...,...,...,...,...,...
2025-07-27 12:00:00,118072.71,118111.34,117890.00,118097.39,298.944250,0.000209,0.001232,118097.39
2025-07-27 13:00:00,118097.39,118217.60,118085.87,118201.99,217.843110,0.000885,0.000846,118201.99
2025-07-27 14:00:00,118201.99,118499.00,118149.96,118422.16,467.709230,0.001861,0.000948,118422.16
2025-07-27 15:00:00,118422.16,118588.00,118236.84,118585.74,601.555060,0.001380,0.003403,118585.75
2025-07-27 16:00:00,118585.75,119530.00,118585.75,119519.99,1742.596320,0.007847,0.010978,NaN

In [126]:
def profcalc(change,tp,sl):
    in_position=False

    profits=[]

    for index,row in df.iterrows():
        if not in_position:
            if row['12h_chg']>change:
                buyprice=row.buyprice
                in_position=True
        if in_position:
            if row.High>= buyprice*tp:
                sellprice=buyprice*tp
                profit=(sellprice-buyprice)/buyprice
                profits.append(float(profit))
                in_position=False
                
            elif row.Low<=buyprice*sl:
                sellprice=buyprice*sl
                profit=(sellprice-buyprice)/buyprice
                profits.append(float(profit))
                in_position=False
    return((pd.Series(profits)+1).prod()-1)

In [127]:
profcalc(0.02,1.07,0.93)

np.float64(11.745685002117234)

In [128]:
arr=np.arange(0.01,0.16,0.01)
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15])

In [129]:
for ele in arr:
    print('for '+str(ele))
    print(profcalc(0.02,1+ele,1-(ele/2)))

for 0.01
-0.9969696327184603
for 0.02
-0.9992873455751526
for 0.03
-0.9813365355478277
for 0.04
-0.8565485121030016
for 0.05
-0.7640789680150675
for 0.060000000000000005
0.5935254728735153
for 0.06999999999999999
3.0440430467494783
for 0.08
8.681640820545171
for 0.09
5.566752227647749
for 0.09999999999999999
3.2012731173642948
for 0.11
4.247795730416905
for 0.12
5.074236838935414
for 0.13
12.03820747916922
for 0.14
9.531211744862873
for 0.15000000000000002
6.8864284209858475