In [1]:
import yfinance as yf
import pandas as pd
import datetime as dt

In [2]:
var=yf.Ticker('AAPL')

In [3]:
var

yfinance.Ticker object <AAPL>

In [4]:
var.history(period='5y')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2017-10-04,36.451230,36.505800,36.173629,36.415638,80655200,0.0,0.0
2017-10-05,36.581726,36.880684,36.550884,36.868820,85135200,0.0,0.0
2017-10-06,36.769160,36.892539,36.671880,36.847458,69630400,0.0,0.0
2017-10-09,36.968468,37.186753,36.892545,36.975586,65051600,0.0,0.0
2017-10-10,37.027778,37.488075,36.800005,36.989815,62468000,0.0,0.0
...,...,...,...,...,...,...,...
2022-09-27,152.740005,154.720001,149.949997,151.759995,84442700,0.0,0.0
2022-09-28,147.639999,150.639999,144.839996,149.839996,146691400,0.0,0.0
2022-09-29,146.100006,146.720001,140.679993,142.479996,128138200,0.0,0.0
2022-09-30,141.279999,143.100006,138.000000,138.199997,124705400,0.0,0.0
2022-10-03,138.210007,143.070007,137.690002,142.449997,114169700,0.0,0.0

In [5]:
var.dividends

Date
2017-11-10    0.1575
2018-02-09    0.1575
2018-05-11    0.1825
2018-08-10    0.1825
2018-11-08    0.1825
2019-02-08    0.1825
2019-05-10    0.1925
2019-08-09    0.1925
2019-11-07    0.1925
2020-02-07    0.1925
2020-05-08    0.2050
2020-08-07    0.2050
2020-11-06    0.2050
2021-02-05    0.2050
2021-05-07    0.2200
2021-08-06    0.2200
2021-11-05    0.2200
2022-02-04    0.2200
2022-05-06    0.2300
2022-08-05    0.2300
Name: Dividends, dtype: float64

In [6]:
tickers=pd.read_html('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')[1]
tickers

,Company,Exchange,Symbol,Industry,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,2.88%
1,American Express,NYSE,AXP,Financial services,1982-08-30,NaN,3.56%
2,Amgen,NASDAQ,AMGN,Biopharmaceutical,2020-08-31,NaN,4.88%
3,Apple,NASDAQ,AAPL,Information technology,2015-03-19,NaN,3.15%
4,Boeing,NYSE,BA,Aerospace and defense,1987-03-12,NaN,3.40%
5,Caterpillar,NYSE,CAT,Construction and Mining,1991-05-06,NaN,4.19%
6,Chevron,NYSE,CVX,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,3.05%
7,Cisco,NASDAQ,CSCO,Information technology,2009-06-08,NaN,1.00%
8,Coca-Cola,NYSE,KO,Drink industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.28%
9,Disney,NYSE,DIS,Broadcasting and entertainment,1991-05-06,NaN,2.32%
10,Dow,NYSE,DOW,Chemical industry,2019-04-02,NaN,1.32%
11,Goldman Sachs,NYSE,GS,Financial services,2013-09-20,NaN,6.22%
12,Home Depot,NYSE,HD,Home Improvement,1999-11-01,NaN,5.90%
13,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31,Also 1925-12-07 to 2008-02-19 under various na...,3.71%
14,IBM,NYSE,IBM,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,2.69%
15,Intel,NASDAQ,INTC,Semiconductor industry,1999-11-01,NaN,0.91%
16,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17,NaN,3.60%
17,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06,NaN,2.45%
18,McDonald's,NYSE,MCD,Food industry,1985-10-30,NaN,4.89%
19,Merck,NYSE,MRK,Pharmaceutical industry,1979-06-29,NaN,1.65%
20,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,NaN,5.43%
21,Nike,NYSE,NKE,Clothing industry,2013-09-20,NaN,2.48%
22,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26,NaN,3.15%
23,Salesforce,NYSE,CRM,Information technology,2020-08-31,NaN,3.38%
24,Travelers,NYSE,TRV,Insurance,2009-06-08,NaN,3.38%
25,UnitedHealth,NYSE,UNH,Managed health care,2012-09-24,NaN,10.14%
26,Verizon,NYSE,VZ,Telecommunications industry,2004-04-08,NaN,0.97%
27,Visa,NYSE,V,Financial services,2013-09-20,NaN,4.06%
28,Walgreens Boots Alliance,NASDAQ,WBA,Retailing,2018-06-26,NaN,0.88%
29,Walmart,NYSE,WMT,Retailing,1997-03-17,NaN,3.04%

In [7]:
tickers=tickers.Symbol.to_list()
tickers

['MMM',
 'AXP',
 'AMGN',
 'AAPL',
 'BA',
 'CAT',
 'CVX',
 'CSCO',
 'KO',
 'DIS',
 'DOW',
 'GS',
 'HD',
 'HON',
 'IBM',
 'INTC',
 'JNJ',
 'JPM',
 'MCD',
 'MRK',
 'MSFT',
 'NKE',
 'PG',
 'CRM',
 'TRV',
 'UNH',
 'VZ',
 'V',
 'WBA',
 'WMT']

In [8]:
divs=[]
for i in tickers:
    inst=yf.Ticker(i)
    inst.history(period='1y')
    divs.append(inst.dividends)

In [9]:
divs

[Date
 2021-11-18    1.48
 2022-02-17    1.49
 2022-05-19    1.49
 2022-08-19    1.49
 Name: Dividends, dtype: float64,
 Date
 2021-10-07    0.43
 2022-01-06    0.43
 2022-04-07    0.52
 2022-06-30    0.52
 Name: Dividends, dtype: float64,
 Date
 2021-11-15    1.76
 2022-02-14    1.94
 2022-05-16    1.94
 2022-08-17    1.94
 Name: Dividends, dtype: float64,
 Date
 2021-11-05    0.22
 2022-02-04    0.22
 2022-05-06    0.23
 2022-08-05    0.23
 Name: Dividends, dtype: float64,
 Series([], Name: Dividends, dtype: int64),
 Date
 2021-10-22    1.11
 2022-01-19    1.11
 2022-04-22    1.11
 2022-07-19    1.20
 Name: Dividends, dtype: float64,
 Date
 2021-11-17    1.34
 2022-02-15    1.42
 2022-05-18    1.42
 2022-08-18    1.42
 Name: Dividends, dtype: float64,
 Date
 2021-10-04    0.37
 2022-01-04    0.37
 2022-04-05    0.38
 2022-07-05    0.38
 Name: Dividends, dtype: float64,
 Date
 2021-11-30    0.42
 2022-03-14    0.44
 2022-06-14    0.44
 2022-09-15    0.44
 Name: Dividends, dtype: float64,
 Series([], Name: Dividends, dtype: int64),
 Date
 2021-11-29    0.7
 2022-02-25    0.7
 2022-05-27    0.7
 2022-08-30    0.7
 Name: Dividends, dtype: float64,
 Date
 2021-12-01    2.0
 2022-03-01    2.0
 2022-05-31    2.0
 2022-08-31    2.5
 Name: Dividends, dtype: float64,
 Date
 2021-12-01    1.65
 2022-03-09    1.90
 2022-06-01    1.90
 2022-08-31    1.90
 Name: Dividends, dtype: float64,
 Date
 2021-11-10    0.98
 2022-02-24    0.98
 2022-05-12    0.98
 2022-08-11    0.98
 Name: Dividends, dtype: float64,
 Date
 2021-11-09    1.64
 2022-02-10    1.64
 2022-05-09    1.65
 2022-08-09    1.65
 Name: Dividends, dtype: float64,
 Date
 2021-11-04    0.348
 2022-02-04    0.365
 2022-05-05    0.365
 2022-08-04    0.365
 Name: Dividends, dtype: float64,
 Date
 2021-11-22    1.06
 2022-02-18    1.06
 2022-05-23    1.13
 2022-08-22    1.13
 Name: Dividends, dtype: float64,
 Date
 2021-10-05    1.0
 2022-01-05    1.0
 2022-04-05    1.0
 2022-07-05    1.0
 Name: Dividends, dtype: float64,
 Date
 2021-11-30    1.38
 2022-02-28    1.38
 2022-06-03    1.38
 2022-08-31    1.38
 Name: Dividends, dtype: float64,
 Date
 2021-12-14    0.69
 2022-03-14    0.69
 2022-06-14    0.69
 2022-09-14    0.69
 Name: Dividends, dtype: float64,
 Date
 2021-11-17    0.62
 2022-02-16    0.62
 2022-05-18    0.62
 2022-08-17    0.62
 Name: Dividends, dtype: float64,
 Date
 2021-12-03    0.305
 2022-03-04    0.305
 2022-06-03    0.305
 2022-09-02    0.305
 Name: Dividends, dtype: float64,
 Date
 2021-10-21    0.870
 2022-01-20    0.870
 2022-04-21    0.913
 2022-07-21    0.913
 Name: Dividends, dtype: float64,
 Series([], Name: Dividends, dtype: int64),
 Date
 2021-12-09    0.88
 2022-03-09    0.88
 2022-06-09    0.93
 2022-09-08    0.93
 Name: Dividends, dtype: float64,
 Date
 2021-12-03    1.45
 2022-03-11    1.45
 2022-06-16    1.65
 2022-09-09    1.65
 Name: Dividends, dtype: float64,
 Date
 2021-10-07    0.64
 2022-01-07    0.64
 2022-04-07    0.64
 2022-07-07    0.64
 Name: Dividends, dtype: float64,
 Date
 2021-11-10    0.375
 2022-02-10    0.375
 2022-05-12    0.375
 2022-08-11    0.375
 Name: Dividends, dtype: float64,
 Date
 2021-11-12    0.478
 2022-02-17    0.478
 2022-05-19    0.478
 2022-08-18    0.480
 Name: Dividends, dtype: float64,
 Date
 2021-12-09    0.55
 2022-03-17    0.56
 2022-05-05    0.56
 2022-08-11    0.56
 Name: Dividends, dtype: float64]

In [10]:
df=pd.DataFrame(divs,index=tickers)
df

Date,2021-10-04,2021-10-05,2021-10-07,2021-10-21,2021-10-22,2021-11-04,2021-11-05,2021-11-09,2021-11-10,2021-11-12,...,2022-08-18,2022-08-19,2022-08-22,2022-08-30,2022-08-31,2022-09-02,2022-09-08,2022-09-09,2022-09-14,2022-09-15
MMM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AXP,NaN,NaN,0.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AMGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAPL,NaN,NaN,NaN,NaN,NaN,NaN,0.22,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAT,NaN,NaN,NaN,NaN,1.11,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CVX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CSCO,0.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.44
DIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,NaN,NaN
GS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.50,NaN,NaN,NaN,NaN,NaN
HD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.90,NaN,NaN,NaN,NaN,NaN
HON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.980,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IBM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.64,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INTC,NaN,NaN,NaN,NaN,NaN,0.348,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JNJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JPM,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MCD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.38,NaN,NaN,NaN,NaN,NaN
MRK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.69,NaN
MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.305,NaN,NaN,NaN,NaN
PG,NaN,NaN,NaN,0.87,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CRM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.93,NaN,NaN,NaN
UNH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.65,NaN,NaN
VZ,NaN,NaN,0.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.375,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.478,...,0.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WMT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.columns=df.columns.month
df.columns

Int64Index([10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12,
            12, 12, 12,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
             2,  2,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,  5,  5,
             5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,
             8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9],
           dtype='int64', name='Date')

In [12]:
df=df.groupby(df.columns,axis=1).sum()
df

Date,1,2,3,4,5,6,7,8,9,10,11,12
MMM,0.00,1.490,0.000,0.000,1.490,0.000,0.000,1.490,0.000,0.00,1.480,0.000
AXP,0.43,0.000,0.000,0.520,0.000,0.520,0.000,0.000,0.000,0.43,0.000,0.000
AMGN,0.00,1.940,0.000,0.000,1.940,0.000,0.000,1.940,0.000,0.00,1.760,0.000
AAPL,0.00,0.220,0.000,0.000,0.230,0.000,0.000,0.230,0.000,0.00,0.220,0.000
BA,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000
CAT,1.11,0.000,0.000,1.110,0.000,0.000,1.200,0.000,0.000,1.11,0.000,0.000
CVX,0.00,1.420,0.000,0.000,1.420,0.000,0.000,1.420,0.000,0.00,1.340,0.000
CSCO,0.37,0.000,0.000,0.380,0.000,0.000,0.380,0.000,0.000,0.37,0.000,0.000
KO,0.00,0.000,0.440,0.000,0.000,0.440,0.000,0.000,0.440,0.00,0.420,0.000
DIS,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000
DOW,0.00,0.700,0.000,0.000,0.700,0.000,0.000,0.700,0.000,0.00,0.700,0.000
GS,0.00,0.000,2.000,0.000,2.000,0.000,0.000,2.500,0.000,0.00,0.000,2.000
HD,0.00,0.000,1.900,0.000,0.000,1.900,0.000,1.900,0.000,0.00,0.000,1.650
HON,0.00,0.980,0.000,0.000,0.980,0.000,0.000,0.980,0.000,0.00,0.980,0.000
IBM,0.00,1.640,0.000,0.000,1.650,0.000,0.000,1.650,0.000,0.00,1.640,0.000
INTC,0.00,0.365,0.000,0.000,0.365,0.000,0.000,0.365,0.000,0.00,0.348,0.000
JNJ,0.00,1.060,0.000,0.000,1.130,0.000,0.000,1.130,0.000,0.00,1.060,0.000
JPM,1.00,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,1.00,0.000,0.000
MCD,0.00,1.380,0.000,0.000,0.000,1.380,0.000,1.380,0.000,0.00,1.380,0.000
MRK,0.00,0.000,0.690,0.000,0.000,0.690,0.000,0.000,0.690,0.00,0.000,0.690
MSFT,0.00,0.620,0.000,0.000,0.620,0.000,0.000,0.620,0.000,0.00,0.620,0.000
NKE,0.00,0.000,0.305,0.000,0.000,0.305,0.000,0.000,0.305,0.00,0.000,0.305
PG,0.87,0.000,0.000,0.913,0.000,0.000,0.913,0.000,0.000,0.87,0.000,0.000
CRM,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000
TRV,0.00,0.000,0.880,0.000,0.000,0.930,0.000,0.000,0.930,0.00,0.000,0.880
UNH,0.00,0.000,1.450,0.000,0.000,1.650,0.000,0.000,1.650,0.00,0.000,1.450
VZ,0.64,0.000,0.000,0.640,0.000,0.000,0.640,0.000,0.000,0.64,0.000,0.000
V,0.00,0.375,0.000,0.000,0.375,0.000,0.000,0.375,0.000,0.00,0.375,0.000
WBA,0.00,0.478,0.000,0.000,0.478,0.000,0.000,0.480,0.000,0.00,0.478,0.000
WMT,0.00,0.000,0.560,0.000,0.560,0.000,0.000,0.560,0.000,0.00,0.000,0.550

In [13]:
df.columns=[dt.date(1900,i,1).strftime('%b') for i in df.columns]

In [14]:
df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
MMM,0.00,1.490,0.000,0.000,1.490,0.000,0.000,1.490,0.000,0.00,1.480,0.000
AXP,0.43,0.000,0.000,0.520,0.000,0.520,0.000,0.000,0.000,0.43,0.000,0.000
AMGN,0.00,1.940,0.000,0.000,1.940,0.000,0.000,1.940,0.000,0.00,1.760,0.000
AAPL,0.00,0.220,0.000,0.000,0.230,0.000,0.000,0.230,0.000,0.00,0.220,0.000
BA,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000
CAT,1.11,0.000,0.000,1.110,0.000,0.000,1.200,0.000,0.000,1.11,0.000,0.000
CVX,0.00,1.420,0.000,0.000,1.420,0.000,0.000,1.420,0.000,0.00,1.340,0.000
CSCO,0.37,0.000,0.000,0.380,0.000,0.000,0.380,0.000,0.000,0.37,0.000,0.000
KO,0.00,0.000,0.440,0.000,0.000,0.440,0.000,0.000,0.440,0.00,0.420,0.000
DIS,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000
DOW,0.00,0.700,0.000,0.000,0.700,0.000,0.000,0.700,0.000,0.00,0.700,0.000
GS,0.00,0.000,2.000,0.000,2.000,0.000,0.000,2.500,0.000,0.00,0.000,2.000
HD,0.00,0.000,1.900,0.000,0.000,1.900,0.000,1.900,0.000,0.00,0.000,1.650
HON,0.00,0.980,0.000,0.000,0.980,0.000,0.000,0.980,0.000,0.00,0.980,0.000
IBM,0.00,1.640,0.000,0.000,1.650,0.000,0.000,1.650,0.000,0.00,1.640,0.000
INTC,0.00,0.365,0.000,0.000,0.365,0.000,0.000,0.365,0.000,0.00,0.348,0.000
JNJ,0.00,1.060,0.000,0.000,1.130,0.000,0.000,1.130,0.000,0.00,1.060,0.000
JPM,1.00,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,1.00,0.000,0.000
MCD,0.00,1.380,0.000,0.000,0.000,1.380,0.000,1.380,0.000,0.00,1.380,0.000
MRK,0.00,0.000,0.690,0.000,0.000,0.690,0.000,0.000,0.690,0.00,0.000,0.690
MSFT,0.00,0.620,0.000,0.000,0.620,0.000,0.000,0.620,0.000,0.00,0.620,0.000
NKE,0.00,0.000,0.305,0.000,0.000,0.305,0.000,0.000,0.305,0.00,0.000,0.305
PG,0.87,0.000,0.000,0.913,0.000,0.000,0.913,0.000,0.000,0.87,0.000,0.000
CRM,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000
TRV,0.00,0.000,0.880,0.000,0.000,0.930,0.000,0.000,0.930,0.00,0.000,0.880
UNH,0.00,0.000,1.450,0.000,0.000,1.650,0.000,0.000,1.650,0.00,0.000,1.450
VZ,0.64,0.000,0.000,0.640,0.000,0.000,0.640,0.000,0.000,0.64,0.000,0.000
V,0.00,0.375,0.000,0.000,0.375,0.000,0.000,0.375,0.000,0.00,0.375,0.000
WBA,0.00,0.478,0.000,0.000,0.478,0.000,0.000,0.480,0.000,0.00,0.478,0.000
WMT,0.00,0.000,0.560,0.000,0.560,0.000,0.000,0.560,0.000,0.00,0.000,0.550

In [15]:
df[df.Jan>0]

       Jan  Feb  Mar    Apr  May   Jun    Jul  Aug  Sep   Oct  Nov  Dec
AXP   0.43  0.0  0.0  0.520  0.0  0.52  0.000  0.0  0.0  0.43  0.0  0.0
CAT   1.11  0.0  0.0  1.110  0.0  0.00  1.200  0.0  0.0  1.11  0.0  0.0
CSCO  0.37  0.0  0.0  0.380  0.0  0.00  0.380  0.0  0.0  0.37  0.0  0.0
JPM   1.00  0.0  0.0  1.000  0.0  0.00  1.000  0.0  0.0  1.00  0.0  0.0
PG    0.87  0.0  0.0  0.913  0.0  0.00  0.913  0.0  0.0  0.87  0.0  0.0
VZ    0.64  0.0  0.0  0.640  0.0  0.00  0.640  0.0  0.0  0.64  0.0  0.0