In [3]:
#How to select all the rows where Namita has said 'No' in SharktankIndiaAllPittches dataframe ?
import pandas as pd
df=pd.read_csv('ShartankIndiaAllPitches.csv')
df

,Episode Number,Pitch Number,Brand,Idea,Investment Amount (In Lakhs INR),Debt (In lakhs INR),Equity,Anupam,Ashneer,Namita,Aman,Peyush,Vineeta,Ghazal,Season
0,1,1,BluePine Industries,Frozen Momos,75,0,18%,N,Y,N,Y,N,Y,N,1
1,1,2,Booz scooters,Renting e-bike for mobility in private spaces,40,0,50%,N,Y,N,N,N,Y,N,1
2,1,3,Heart up my Sleeves,Detachable Sleeves,25,0,30%,Y,N,N,N,N,Y,N,1
3,2,4,Tagz Foods,Healthy Potato Chips,70,0,2.75%,N,Y,N,N,N,N,N,1
4,2,5,Head and Heart,Brain Development Course,0,0,0,N,N,N,N,N,N,N,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,34,113,Green Protein,Plant-Based Protein,0,0,0,N,N,N,N,N,N,N,1
113,34,114,On2Cook,Fastest Cooking Device,0,0,0,N,N,N,N,N,N,N,1
114,35,115,Jain Shikanji,Lemonade,40,0,30.00%,Y,Y,N,Y,N,Y,N,1
115,35,116,Woloo,Washroom Finder,0,0,0,N,N,N,N,N,N,N,1
116,35,117,Elcare India,Carenting for Elders,0,0,0,N,N,N,N,N,N,N,1

In [4]:
df['Namita']=='N'

0      True
1      True
2      True
3      True
4      True
       ...
112    True
113    True
114    True
115    True
116    True
Name: Namita, Length: 117, dtype: bool

In [6]:
import numpy as np
np.where(df['Namita']=='N')

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  13,
         14,  17,  18,  19,  20,  21,  22,  23,  25,  26,  28,  29,  30,
         31,  34,  35,  37,  38,  40,  41,  42,  43,  45,  46,  48,  51,
         52,  53,  54,  55,  56,  57,  59,  60,  61,  62,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  80,
         81,  82,  84,  86,  87,  88,  89,  90,  92,  93,  94,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 107, 108, 109, 111, 112,
        113, 114, 115, 116], dtype=int64),)

In [7]:
df.loc[df['Namita'] == 'N']

,Episode Number,Pitch Number,Brand,Idea,Investment Amount (In Lakhs INR),Debt (In lakhs INR),Equity,Anupam,Ashneer,Namita,Aman,Peyush,Vineeta,Ghazal,Season
0,1,1,BluePine Industries,Frozen Momos,75,0,18%,N,Y,N,Y,N,Y,N,1
1,1,2,Booz scooters,Renting e-bike for mobility in private spaces,40,0,50%,N,Y,N,N,N,Y,N,1
2,1,3,Heart up my Sleeves,Detachable Sleeves,25,0,30%,Y,N,N,N,N,Y,N,1
3,2,4,Tagz Foods,Healthy Potato Chips,70,0,2.75%,N,Y,N,N,N,N,N,1
4,2,5,Head and Heart,Brain Development Course,0,0,0,N,N,N,N,N,N,N,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,34,113,Green Protein,Plant-Based Protein,0,0,0,N,N,N,N,N,N,N,1
113,34,114,On2Cook,Fastest Cooking Device,0,0,0,N,N,N,N,N,N,N,1
114,35,115,Jain Shikanji,Lemonade,40,0,30.00%,Y,Y,N,Y,N,Y,N,1
115,35,116,Woloo,Washroom Finder,0,0,0,N,N,N,N,N,N,N,1
116,35,117,Elcare India,Carenting for Elders,0,0,0,N,N,N,N,N,N,N,1