In [1]:
import yfinance as yf
import pandas as pd
import datetime as dt
import sqlalchemy
from pandas.tseries.offsets import MonthEnd

In [2]:
wiki='https://en.wikipedia.org/wiki/List_of_BSE_SENSEX_companies'
tickersSensex=pd.read_html(wiki)[0].Symbol.to_list()
tickersSensex

['ASIANPAINT.BO',
 'AXISBANK.BO',
 'BAJAJ-AUTO.BO',
 'BAJFINANCE.BO',
 'BAJAJFINSV.BO',
 'BHARTIARTL.BO',
 'DRREDDY.BO',
 'HCLTECH.BO',
 'HDFC.BO',
 'HDFCBANK.BO',
 'HINDUNILVR.BO',
 'ICICIBANK.BO',
 'INDUSINDBK.BO',
 'INFY.BO',
 'ITC.BO',
 'KOTAKBANK.BO',
 'LT.BO',
 'M&M.BO',
 'MARUTI.BO',
 'NESTLEIND.BO',
 'NTPC.BO',
 'ONGC.BO',
 'POWERGRID.BO',
 'RELIANCE.BO',
 'SBIN.BO',
 'SUNPHARMA.BO',
 'TCS.BO',
 'TECHM.BO',
 'TITAN.BO',
 'ULTRACEMCO.BO']

In [3]:
data=pd.DataFrame()

for ticker in tickersSensex:
    data[ticker]=(yf.download(ticker)['Adj Close'])

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [4]:
data

,ASIANPAINT.BO,AXISBANK.BO,BAJAJ-AUTO.BO,BAJFINANCE.BO,BAJAJFINSV.BO,BHARTIARTL.BO,DRREDDY.BO,HCLTECH.BO,HDFC.BO,HDFCBANK.BO,...,NTPC.BO,ONGC.BO,POWERGRID.BO,RELIANCE.BO,SBIN.BO,SUNPHARMA.BO,TCS.BO,TECHM.BO,TITAN.BO,ULTRACEMCO.BO
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,17.608315,3.698819,NaN,NaN,348.429749,NaN,333.680023,11.767922,20.748421,14.642578,...,NaN,8.365726,NaN,36.653233,16.367941,11.582288,NaN,NaN,5.972432,406.405823
2000-01-04,17.610577,3.841632,NaN,NaN,362.600342,NaN,352.942169,12.709071,20.405815,14.608990,...,NaN,8.165368,NaN,39.579964,17.514439,11.241292,NaN,NaN,5.795073,403.634827
2000-01-05,17.429956,3.741663,NaN,NaN,364.904877,NaN,334.033539,11.852129,19.616447,14.147217,...,NaN,8.817500,NaN,41.468189,16.772589,10.865538,NaN,NaN,5.342031,397.169281
2000-01-06,17.159021,3.648836,NaN,NaN,392.755646,NaN,360.751953,11.742966,19.757523,14.063257,...,NaN,8.642684,NaN,42.550289,17.467232,10.857711,NaN,NaN,5.758442,428.896667
2000-01-07,17.294487,3.470320,NaN,NaN,395.207275,NaN,331.901703,10.804155,19.146185,14.231174,...,NaN,8.271441,NaN,45.535126,18.809313,10.078022,NaN,NaN,5.573371,463.164124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-10,3045.949951,843.400024,3722.600098,6978.549805,1700.199951,825.299988,4547.549805,1052.750000,2504.850098,1525.250000,...,172.100006,139.850006,209.635986,2574.449951,605.700012,1010.900024,3206.000000,1021.450012,2636.850098,6801.500000
2022-11-11,3054.600098,850.950012,3726.449951,7051.049805,1718.250000,826.450012,4544.700195,1090.250000,2651.250000,1610.949951,...,171.449997,140.449997,209.050003,2631.350098,601.099976,1013.450012,3316.100098,1058.599976,2652.350098,6812.049805
2022-11-14,3054.649902,851.250000,3724.550049,7023.299805,1718.349976,821.650024,4365.750000,1098.500000,2661.500000,1614.400024,...,171.250000,139.199997,211.250000,2617.949951,592.549988,1016.349976,3334.050049,1065.849976,2629.699951,6854.799805
2022-11-15,3081.800049,858.400024,3763.649902,7024.450195,1705.349976,835.099976,4436.649902,1103.550049,2676.699951,1619.349976,...,171.949997,142.350006,215.899994,2606.699951,600.900024,1013.000000,3332.649902,1066.699951,2657.050049,6961.399902
2022-11-16,3083.800049,854.650024,3747.000000,6891.850098,1685.750000,840.950012,4477.649902,1105.300049,2696.449951,1632.250000,...,169.899994,142.899994,217.199997,2591.850098,599.599976,1021.099976,3354.050049,1067.250000,2643.449951,6908.850098

In [5]:
tickersSensex.index('HDFC.BO')

8

In [6]:
df=data.groupby('Date').sum()

In [7]:
df

,ASIANPAINT.BO,AXISBANK.BO,BAJAJ-AUTO.BO,BAJFINANCE.BO,BAJAJFINSV.BO,BHARTIARTL.BO,DRREDDY.BO,HCLTECH.BO,HDFC.BO,HDFCBANK.BO,...,NTPC.BO,ONGC.BO,POWERGRID.BO,RELIANCE.BO,SBIN.BO,SUNPHARMA.BO,TCS.BO,TECHM.BO,TITAN.BO,ULTRACEMCO.BO
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,17.608315,3.698819,0.000000,0.000000,348.429749,0.000000,333.680023,11.767922,20.748421,14.642578,...,0.000000,8.365726,0.000000,36.653233,16.367941,11.582288,0.000000,0.000000,5.972432,406.405823
2000-01-04,17.610577,3.841632,0.000000,0.000000,362.600342,0.000000,352.942169,12.709071,20.405815,14.608990,...,0.000000,8.165368,0.000000,39.579964,17.514439,11.241292,0.000000,0.000000,5.795073,403.634827
2000-01-05,17.429956,3.741663,0.000000,0.000000,364.904877,0.000000,334.033539,11.852129,19.616447,14.147217,...,0.000000,8.817500,0.000000,41.468189,16.772589,10.865538,0.000000,0.000000,5.342031,397.169281
2000-01-06,17.159021,3.648836,0.000000,0.000000,392.755646,0.000000,360.751953,11.742966,19.757523,14.063257,...,0.000000,8.642684,0.000000,42.550289,17.467232,10.857711,0.000000,0.000000,5.758442,428.896667
2000-01-07,17.294487,3.470320,0.000000,0.000000,395.207275,0.000000,331.901703,10.804155,19.146185,14.231174,...,0.000000,8.271441,0.000000,45.535126,18.809313,10.078022,0.000000,0.000000,5.573371,463.164124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-10,3045.949951,843.400024,3722.600098,6978.549805,1700.199951,825.299988,4547.549805,1052.750000,2504.850098,1525.250000,...,172.100006,139.850006,209.635986,2574.449951,605.700012,1010.900024,3206.000000,1021.450012,2636.850098,6801.500000
2022-11-11,3054.600098,850.950012,3726.449951,7051.049805,1718.250000,826.450012,4544.700195,1090.250000,2651.250000,1610.949951,...,171.449997,140.449997,209.050003,2631.350098,601.099976,1013.450012,3316.100098,1058.599976,2652.350098,6812.049805
2022-11-14,3054.649902,851.250000,3724.550049,7023.299805,1718.349976,821.650024,4365.750000,1098.500000,2661.500000,1614.400024,...,171.250000,139.199997,211.250000,2617.949951,592.549988,1016.349976,3334.050049,1065.849976,2629.699951,6854.799805
2022-11-15,3081.800049,858.400024,3763.649902,7024.450195,1705.349976,835.099976,4436.649902,1103.550049,2676.699951,1619.349976,...,171.949997,142.350006,215.899994,2606.699951,600.900024,1013.000000,3332.649902,1066.699951,2657.050049,6961.399902
2022-11-16,3083.800049,854.650024,3747.000000,6891.850098,1685.750000,840.950012,4477.649902,1105.300049,2696.449951,1632.250000,...,169.899994,142.899994,217.199997,2591.850098,599.599976,1021.099976,3354.050049,1067.250000,2643.449951,6908.850098

In [8]:
mtlprice=df.resample('M').last()#taking the monthly last Price

In [9]:
mtlprice

,ASIANPAINT.BO,AXISBANK.BO,BAJAJ-AUTO.BO,BAJFINANCE.BO,BAJAJFINSV.BO,BHARTIARTL.BO,DRREDDY.BO,HCLTECH.BO,HDFC.BO,HDFCBANK.BO,...,NTPC.BO,ONGC.BO,POWERGRID.BO,RELIANCE.BO,SBIN.BO,SUNPHARMA.BO,TCS.BO,TECHM.BO,TITAN.BO,ULTRACEMCO.BO
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-31,20.771452,4.420019,0.000000,0.000000,352.793640,0.000000,294.609467,78.153915,23.069901,19.743132,...,0.000000,8.281262,0.000000,47.786465,16.496082,12.330976,0.000000,0.000000,5.226361,350.063232
2000-02-29,16.933239,5.226903,0.000000,0.000000,292.482849,0.000000,332.094482,82.421066,27.164282,18.269638,...,0.000000,6.464334,0.000000,45.237362,15.325980,16.633043,0.000000,0.000000,3.855671,294.736603
2000-03-31,19.376884,5.648197,0.000000,2.439876,376.574768,0.000000,345.303772,67.796921,26.423004,21.493694,...,0.000000,5.329000,0.000000,45.680370,13.562391,12.108003,0.000000,0.000000,3.470103,279.865875
2000-04-30,18.515182,5.209717,0.000000,2.167984,349.116150,0.000000,276.840942,62.769531,33.419983,20.854046,...,0.000000,4.489161,0.000000,51.278881,14.070360,6.962101,0.000000,0.000000,2.748848,332.513824
2000-05-31,19.376884,5.320560,0.000000,2.150096,357.942139,0.000000,297.453735,48.079105,33.497707,19.322464,...,0.000000,5.199263,0.000000,50.805851,13.892855,8.324251,0.000000,0.000000,2.923883,252.987686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-07-31,3327.548340,724.799988,3913.399902,7208.899902,15039.299805,674.900024,4090.350098,939.352722,2379.100098,1434.449951,...,150.067764,131.028000,206.967209,2501.217529,528.200012,940.458923,3292.275391,1030.979492,2353.050049,6508.543457
2022-08-31,3386.712891,751.150024,4085.100098,7303.799805,16966.699219,726.500000,4244.600098,930.045776,2446.199951,1486.199951,...,163.850006,138.550003,224.236786,2639.100098,531.150024,893.250000,3203.305908,1058.304443,2602.699951,6672.500000
2022-09-30,3337.333984,733.500000,3527.100098,7337.549805,1678.599976,799.750000,4333.950195,923.313171,2289.500000,1422.400024,...,159.750000,126.849998,207.194382,2377.699951,531.049988,949.000000,2996.840332,990.974854,2606.550049,6249.850098
2022-10-31,3106.800049,905.849976,3669.250000,7139.700195,1687.750000,832.000000,4431.399902,1041.599976,2469.750000,1496.400024,...,173.100006,134.000000,222.771820,2549.550049,573.799988,1015.950012,3193.050049,1045.330078,2753.050049,6713.350098
2022-11-30,3083.800049,854.650024,3747.000000,6891.850098,1685.750000,840.950012,4477.649902,1105.300049,2696.449951,1632.250000,...,169.899994,142.899994,217.199997,2591.850098,599.599976,1021.099976,3354.050049,1067.250000,2643.449951,6908.850098

In [10]:
formation=dt.datetime(2011,2,28)

In [11]:
begin_measurement=formation-MonthEnd(12)

In [12]:
begin_measurement

Timestamp('2010-02-28 00:00:00')

In [13]:
end_measurement=formation-MonthEnd(1)
end_measurement

Timestamp('2011-01-31 00:00:00')

In [14]:
price_end=mtlprice.loc[end_measurement]
price_end

ASIANPAINT.BO     233.503937
AXISBANK.BO       229.892731
BAJAJ-AUTO.BO     903.230347
BAJFINANCE.BO      53.569870
BAJAJFINSV.BO     402.097107
BHARTIARTL.BO     276.945984
DRREDDY.BO       1480.101562
HCLTECH.BO         98.301682
HDFC.BO           532.563171
HDFCBANK.BO       187.734787
HINDUNILVR.BO     218.277069
ICICIBANK.BO      158.631714
INDUSINDBK.BO     209.603500
INFY.BO           299.139893
ITC.BO             81.633949
KOTAKBANK.BO      190.707916
LT.BO             606.981689
M&M.BO            324.000732
MARUTI.BO        1134.466675
NESTLEIND.BO     2855.625488
NTPC.BO            98.196053
ONGC.BO           123.756485
POWERGRID.BO       69.787384
RELIANCE.BO       419.734894
SBIN.BO           233.222839
SUNPHARMA.BO      204.972794
TCS.BO            465.039062
TECHM.BO          129.893570
TITAN.BO          167.751144
ULTRACEMCO.BO     954.288513
Name: 2011-01-31 00:00:00, dtype: float64

In [15]:
price_12monthbefore=mtlprice.loc[begin_measurement]
price_12monthbefore

ASIANPAINT.BO     162.645981
AXISBANK.BO       205.349792
BAJAJ-AUTO.BO     646.406494
BAJFINANCE.BO      26.924740
BAJAJFINSV.BO     339.605469
BHARTIARTL.BO     242.024445
DRREDDY.BO       1033.025635
HCLTECH.BO         72.239075
HDFC.BO           417.694000
HDFCBANK.BO       155.655884
HINDUNILVR.BO     185.383011
ICICIBANK.BO      133.623657
INDUSINDBK.BO     138.627441
INFY.BO           245.787445
ITC.BO             57.022148
KOTAKBANK.BO      183.827362
LT.BO             575.449463
M&M.BO            228.908142
MARUTI.BO        1318.916260
NESTLEIND.BO     2217.154297
NTPC.BO           103.557602
ONGC.BO           113.300583
POWERGRID.BO       76.915306
RELIANCE.BO       443.565369
SBIN.BO           172.953491
SUNPHARMA.BO      142.246811
TCS.BO            300.130371
TECHM.BO          177.828827
TITAN.BO           81.160851
ULTRACEMCO.BO     985.429199
Name: 2010-02-28 00:00:00, dtype: float64

In [16]:
ret_12=price_end/price_12monthbefore-1

In [17]:
ret_12#return over the last 12 month, skipping the most recent month

ASIANPAINT.BO    0.435658
AXISBANK.BO      0.119518
BAJAJ-AUTO.BO    0.397310
BAJFINANCE.BO    0.989615
BAJAJFINSV.BO    0.184012
BHARTIARTL.BO    0.144289
DRREDDY.BO       0.432783
HCLTECH.BO       0.360783
HDFC.BO          0.275008
HDFCBANK.BO      0.206089
HINDUNILVR.BO    0.177438
ICICIBANK.BO     0.187153
INDUSINDBK.BO    0.511991
INFY.BO          0.217067
ITC.BO           0.431618
KOTAKBANK.BO     0.037429
LT.BO            0.054796
M&M.BO           0.415418
MARUTI.BO       -0.139849
NESTLEIND.BO     0.287969
NTPC.BO         -0.051774
ONGC.BO          0.092285
POWERGRID.BO    -0.092672
RELIANCE.BO     -0.053725
SBIN.BO          0.348471
SUNPHARMA.BO     0.440966
TCS.BO           0.549457
TECHM.BO        -0.269558
TITAN.BO         1.066897
ULTRACEMCO.BO   -0.031601
dtype: float64

In [18]:
winners=ret_12.nlargest(3)
winners

TITAN.BO         1.066897
BAJFINANCE.BO    0.989615
TCS.BO           0.549457
dtype: float64

In [19]:
233.503937/162.645996-1

0.4356574569471727

In [20]:
winners.index

Index(['TITAN.BO', 'BAJFINANCE.BO', 'TCS.BO'], dtype='object')

In [21]:
winnerret=mtlprice.loc[formation+MonthEnd(1),winners.index]/mtlprice.loc[formation,winners.index]-1
winnerret

TITAN.BO         0.144881
BAJFINANCE.BO    0.143477
TCS.BO           0.062492
dtype: float64

In [22]:
Momentumprofit=winnerret.mean()
Momentumprofit

0.11694972039915437

In [23]:
def momentumprofit(formation,holdingperiod=1):
    begin_measurement=formation-MonthEnd(12)
    end_measurement=formation-MonthEnd(1)
    price_end=mtlprice.loc[end_measurement]
    price_12mbefore=mtlprice.loc[begin_measurement]
    ret_12=price_end/price_12monthbefore-1
    winners=ret_12.nlargest(3)
    winnerret=mtlprice.loc[formation+MonthEnd(holdingperiod),winners.index]/mtlprice.loc[formation,winners.index]-1
    Momentumprofit=winnerret.mean()
    return Momentumprofit

In [24]:
formation

datetime.datetime(2011, 2, 28, 0, 0)

In [25]:
momentumprofit(formation)

0.11694972039915437

In [26]:
profit,dates,holding=[],[],[]

In [27]:
for i in (1,3,6):
    for j in mtlprice.index[12:-i]:
        profit.append(momentumprofit(j,holdingperiod=i))
        dates.append(j + MonthEnd(i))
        holding.append(i)

In [28]:
frame=pd.DataFrame({'Momentumprofit':profit,'holdingperiod':holding},index=dates)
frame

            Momentumprofit  holdingperiod
2001-02-28             NaN              1
2001-03-31             NaN              1
2001-04-30             NaN              1
2001-05-31             NaN              1
2001-06-30             NaN              1
...                    ...            ...
2022-07-31       -0.002651              6
2022-08-31        0.044441              6
2022-09-30       -0.285225              6
2022-10-31       -0.229791              6
2022-11-30       -0.178446              6

[779 rows x 2 columns]

In [29]:
frame.groupby('holdingperiod').mean()

               Momentumprofit
holdingperiod
1                    0.016793
3                    0.052413
6                    0.109436

In [30]:
#if we holds a assest for 1 month we get 1.6% return 6 month 10%, So indian market seems to be  a momentum market

In [31]:
for i in (1,3,6):
    for j in mtlprice.index[12:-i]:
        print(i)
        print(j)

1
2001-01-31 00:00:00
1
2001-02-28 00:00:00
1
2001-03-31 00:00:00
1
2001-04-30 00:00:00
1
2001-05-31 00:00:00
1
2001-06-30 00:00:00
1
2001-07-31 00:00:00
1
2001-08-31 00:00:00
1
2001-09-30 00:00:00
1
2001-10-31 00:00:00
1
2001-11-30 00:00:00
1
2001-12-31 00:00:00
1
2002-01-31 00:00:00
1
2002-02-28 00:00:00
1
2002-03-31 00:00:00
1
2002-04-30 00:00:00
1
2002-05-31 00:00:00
1
2002-06-30 00:00:00
1
2002-07-31 00:00:00
1
2002-08-31 00:00:00
1
2002-09-30 00:00:00
1
2002-10-31 00:00:00
1
2002-11-30 00:00:00
1
2002-12-31 00:00:00
1
2003-01-31 00:00:00
1
2003-02-28 00:00:00
1
2003-03-31 00:00:00
1
2003-04-30 00:00:00
1
2003-05-31 00:00:00
1
2003-06-30 00:00:00
1
2003-07-31 00:00:00
1
2003-08-31 00:00:00
1
2003-09-30 00:00:00
1
2003-10-31 00:00:00
1
2003-11-30 00:00:00
1
2003-12-31 00:00:00
1
2004-01-31 00:00:00
1
2004-02-29 00:00:00
1
2004-03-31 00:00:00
1
2004-04-30 00:00:00
1
2004-05-31 00:00:00
1
2004-06-30 00:00:00
1
2004-07-31 00:00:00
1
2004-08-31 00:00:00
1
2004-09-30 00:00:00
1
2004-10-31 00:00:00
1
2004-11-30 00:00:00
1
2004-12-31 00:00:00
1
2005-01-31 00:00:00
1
2005-02-28 00:00:00
1
2005-03-31 00:00:00
1
2005-04-30 00:00:00
1
2005-05-31 00:00:00
1
2005-06-30 00:00:00
1
2005-07-31 00:00:00
1
2005-08-31 00:00:00
1
2005-09-30 00:00:00
1
2005-10-31 00:00:00
1
2005-11-30 00:00:00
1
2005-12-31 00:00:00
1
2006-01-31 00:00:00
1
2006-02-28 00:00:00
1
2006-03-31 00:00:00
1
2006-04-30 00:00:00
1
2006-05-31 00:00:00
1
2006-06-30 00:00:00
1
2006-07-31 00:00:00
1
2006-08-31 00:00:00
1
2006-09-30 00:00:00
1
2006-10-31 00:00:00
1
2006-11-30 00:00:00
1
2006-12-31 00:00:00
1
2007-01-31 00:00:00
1
2007-02-28 00:00:00
1
2007-03-31 00:00:00
1
2007-04-30 00:00:00
1
2007-05-31 00:00:00
1
2007-06-30 00:00:00
1
2007-07-31 00:00:00
1
2007-08-31 00:00:00
1
2007-09-30 00:00:00
1
2007-10-31 00:00:00
1
2007-11-30 00:00:00
1
2007-12-31 00:00:00
1
2008-01-31 00:00:00
1
2008-02-29 00:00:00
1
2008-03-31 00:00:00
1
2008-04-30 00:00:00
1
2008-05-31 00:00:00
1
2008-06-30 00:00:00
1
2008-07-31 00:00:00
1
2008-08-31 00:00:00
1
2008-09-30 00:00:00
1
2008-10-31 00:00:00
1
2008-11-30 00:00:00
1
2008-12-31 00:00:00
1
2009-01-31 00:00:00
1
2009-02-28 00:00:00
1
2009-03-31 00:00:00
1
2009-04-30 00:00:00
1
2009-05-31 00:00:00
1
2009-06-30 00:00:00
1
2009-07-31 00:00:00
1
2009-08-31 00:00:00
1
2009-09-30 00:00:00
1
2009-10-31 00:00:00
1
2009-11-30 00:00:00
1
2009-12-31 00:00:00
1
2010-01-31 00:00:00
1
2010-02-28 00:00:00
1
2010-03-31 00:00:00
1
2010-04-30 00:00:00
1
2010-05-31 00:00:00
1
2010-06-30 00:00:00
1
2010-07-31 00:00:00
1
2010-08-31 00:00:00
1
2010-09-30 00:00:00
1
2010-10-31 00:00:00
1
2010-11-30 00:00:00
1
2010-12-31 00:00:00
1
2011-01-31 00:00:00
1
2011-02-28 00:00:00
1
2011-03-31 00:00:00
1
2011-04-30 00:00:00
1
2011-05-31 00:00:00
1
2011-06-30 00:00:00
1
2011-07-31 00:00:00
1
2011-08-31 00:00:00
1
2011-09-30 00:00:00
1
2011-10-31 00:00:00
1
2011-11-30 00:00:00
1
2011-12-31 00:00:00
1
2012-01-31 00:00:00
1
2012-02-29 00:00:00
1
2012-03-31 00:00:00
1
2012-04-30 00:00:00
1
2012-05-31 00:00:00
1
2012-06-30 00:00:00
1
2012-07-31 00:00:00
1
2012-08-31 00:00:00
1
2012-09-30 00:00:00
1
2012-10-31 00:00:00
1
2012-11-30 00:00:00
1
2012-12-31 00:00:00
1
2013-01-31 00:00:00
1
2013-02-28 00:00:00
1
2013-03-31 00:00:00
1
2013-04-30 00:00:00
1
2013-05-31 00:00:00
1
2013-06-30 00:00:00
1
2013-07-31 00:00:00
1
2013-08-31 00:00:00
1
2013-09-30 00:00:00
1
2013-10-31 00:00:00
1
2013-11-30 00:00:00
1
2013-12-31 00:00:00
1
2014-01-31 00:00:00
1
2014-02-28 00:00:00
1
2014-03-31 00:00:00
1
2014-04-30 00:00:00
1
2014-05-31 00:00:00
1
2014-06-30 00:00:00
1
2014-07-31 00:00:00
1
2014-08-31 00:00:00
1
2014-09-30 00:00:00
1
2014-10-31 00:00:00
1
2014-11-30 00:00:00
1
2014-12-31 00:00:00
1
2015-01-31 00:00:00
1
2015-02-28 00:00:00
1
2015-03-31 00:00:00
1
2015-04-30 00:00:00
1
2015-05-31 00:00:00
1
2015-06-30 00:00:00
1
2015-07-31 00:00:00
1
2015-08-31 00:00:00
1
2015-09-30 00:00:00
1
2015-10-31 00:00:00
1
2015-11-30 00:00:00
1
2015-12-31 00:00:00
1
2016-01-31 00:00:00
1
2016-02-29 00:00:00
1
2016-03-31 00:00:00
1
2016-04-30 00:00:00
1
2016-05-31 00:00:00
1
2016-06-30 00:00:00
1
2016-07-31 00:00:00
1
2016-08-31 00:00:00
1
2016-09-30 00:00:00
1
2016-10-31 00:00:00
1
2016-11-30 00:00:00
1
2016-12-31 00:00:00
1
2017-01-31 00:00:00
1
2017-02-28 00:00:00
1
2017-03-31 00:00:00
1
2017-04-30 00:00:00
1
2017-05-31 00:00:00
1
2017-06-30 00:00:00
1
2017-07-31 00:00:00
1
2017-08-31 00:00:00
1
2017-09-30 00:00:00
1
2017-10-31 00:00:00
1
2017-11-30 00:00:00
1
2017-12-31 00:00:00
1
2018-01-31 00:00:00
1
2018-02-28 00:00:00
1
2018-03-31 00:00:00
1
2018-04-30 00:00:00
1
2018-05-31 00:00:00
1
2018-06-30 00:00:00
1
2018-07-31 00:00:00
1
2018-08-31 00:00:00
1
2018-09-30 00:00:00
1
2018-10-31 00:00:00
1
2018-11-30 00:00:00
1
2018-12-31 00:00:00
1
2019-01-31 00:00:00
1
2019-02-28 00:00:00
1
2019-03-31 00:00:00
1
2019-04-30 00:00:00
1
2019-05-31 00:00:00
1
2019-06-30 00:00:00
1
2019-07-31 00:00:00
1
2019-08-31 00:00:00
1
2019-09-30 00:00:00
1
2019-10-31 00:00:00
1
2019-11-30 00:00:00
1
2019-12-31 00:00:00
1
2020-01-31 00:00:00
1
2020-02-29 00:00:00
1
2020-03-31 00:00:00
1
2020-04-30 00:00:00
1
2020-05-31 00:00:00
1
2020-06-30 00:00:00
1
2020-07-31 00:00:00
1
2020-08-31 00:00:00
1
2020-09-30 00:00:00
1
2020-10-31 00:00:00
1
2020-11-30 00:00:00
1
2020-12-31 00:00:00
1
2021-01-31 00:00:00
1
2021-02-28 00:00:00
1
2021-03-31 00:00:00
1
2021-04-30 00:00:00
1
2021-05-31 00:00:00
1
2021-06-30 00:00:00
1
2021-07-31 00:00:00
1
2021-08-31 00:00:00
1
2021-09-30 00:00:00
1
2021-10-31 00:00:00
1
2021-11-30 00:00:00
1
2021-12-31 00:00:00
1
2022-01-31 00:00:00
1
2022-02-28 00:00:00
1
2022-03-31 00:00:00
1
2022-04-30 00:00:00
1
2022-05-31 00:00:00
1
2022-06-30 00:00:00
1
2022-07-31 00:00:00
1
2022-08-31 00:00:00
1
2022-09-30 00:00:00
1
2022-10-31 00:00:00
3
2001-01-31 00:00:00
3
2001-02-28 00:00:00
3
2001-03-31 00:00:00
3
2001-04-30 00:00:00
3
2001-05-31 00:00:00
3
2001-06-30 00:00:00
3
2001-07-31 00:00:00
3
2001-08-31 00:00:00
3
2001-09-30 00:00:00
3
2001-10-31 00:00:00
3
2001-11-30 00:00:00
3
2001-12-31 00:00:00
3
2002-01-31 00:00:00
3
2002-02-28 00:00:00
3
2002-03-31 00:00:00
3
2002-04-30 00:00:00
3
2002-05-31 00:00:00
3
2002-06-30 00:00:00
3
2002-07-31 00:00:00
3
2002-08-31 00:00:00
3
2002-09-30 00:00:00
3
2002-10-31 00:00:00
3
2002-11-30 00:00:00
3
2002-12-31 00:00:00
3
2003-01-31 00:00:00
3
2003-02-28 00:00:00
3
2003-03-31 00:00:00
3
2003-04-30 00:00:00
3
2003-05-31 00:00:00
3
2003-06-30 00:00:00
3
2003-07-31 00:00:00
3
2003-08-31 00:00:00
3
2003-09-30 00:00:00
3
2003-10-31 00:00:00
3
2003-11-30 00:00:00
3
2003-12-31 00:00:00
3
2004-01-31 00:00:00
3
2004-02-29 00:00:00
3
2004-03-31 00:00:00
3
2004-04-30 00:00:00
3
2004-05-31 00:00:00
3
2004-06-30 00:00:00
3
2004-07-31 00:00:00
3
2004-08-31 00:00:00
3
2004-09-30 00:00:00
3
2004-10-31 00:00:00
3
2004-11-30 00:00:00
3
2004-12-31 00:00:00
3
2005-01-31 00:00:00
3
2005-02-28 00:00:00
3
2005-03-31 00:00:00
3
2005-04-30 00:00:00
3
2005-05-31 00:00:00
3
2005-06-30 00:00:00
3
2005-07-31 00:00:00
3
2005-08-31 00:00:00
3
2005-09-30 00:00:00
3
2005-10-31 00:00:00
3
2005-11-30 00:00:00
3
2005-12-31 00:00:00
3
2006-01-31 00:00:00
3
2006-02-28 00:00:00
3
2006-03-31 00:00:00
3
2006-04-30 00:00:00
3
2006-05-31 00:00:00
3
2006-06-30 00:00:00
3
2006-07-31 00:00:00
3
2006-08-31 00:00:00
3
2006-09-30 00:00:00
3
2006-10-31 00:00:00
3
2006-11-30 00:00:00
3
2006-12-31 00:00:00
3
2007-01-31 00:00:00
3
2007-02-28 00:00:00
3
2007-03-31 00:00:00
3
2007-04-30 00:00:00
3
2007-05-31 00:00:00
3
2007-06-30 00:00:00
3
2007-07-31 00:00:00
3
2007-08-31 00:00:00
3
2007-09-30 00:00:00
3
2007-10-31 00:00:00
3
2007-11-30 00:00:00
3
2007-12-31 00:00:00
3
2008-01-31 00:00:00
3
2008-02-29 00:00:00
3
2008-03-31 00:00:00
3
2008-04-30 00:00:00
3
2008-05-31 00:00:00
3
2008-06-30 00:00:00
3
2008-07-31 00:00:00
3
2008-08-31 00:00:00
3
2008-09-30 00:00:00
3
2008-10-31 00:00:00
3
2008-11-30 00:00:00
3
2008-12-31 00:00:00
3
2009-01-31 00:00:00
3
2009-02-28 00:00:00
3
2009-03-31 00:00:00
3
2009-04-30 00:00:00
3
2009-05-31 00:00:00
3
2009-06-30 00:00:00
3
2009-07-31 00:00:00
3
2009-08-31 00:00:00
3
2009-09-30 00:00:00
3
2009-10-31 00:00:00
3
2009-11-30 00:00:00
3
2009-12-31 00:00:00
3
2010-01-31 00:00:00
3
2010-02-28 00:00:00
3
2010-03-31 00:00:00
3
2010-04-30 00:00:00
3
2010-05-31 00:00:00
3
2010-06-30 00:00:00
3
2010-07-31 00:00:00
3
2010-08-31 00:00:00
3
2010-09-30 00:00:00
3
2010-10-31 00:00:00
3
2010-11-30 00:00:00
3
2010-12-31 00:00:00
3
2011-01-31 00:00:00
3
2011-02-28 00:00:00
3
2011-03-31 00:00:00
3
2011-04-30 00:00:00
3
2011-05-31 00:00:00
3
2011-06-30 00:00:00
3
2011-07-31 00:00:00
3
2011-08-31 00:00:00
3
2011-09-30 00:00:00
3
2011-10-31 00:00:00
3
2011-11-30 00:00:00
3
2011-12-31 00:00:00
3
2012-01-31 00:00:00
3
2012-02-29 00:00:00
3
2012-03-31 00:00:00
3
2012-04-30 00:00:00
3
2012-05-31 00:00:00
3
2012-06-30 00:00:00
3
2012-07-31 00:00:00
3
2012-08-31 00:00:00
3
2012-09-30 00:00:00
3
2012-10-31 00:00:00
3
2012-11-30 00:00:00
3
2012-12-31 00:00:00
3
2013-01-31 00:00:00
3
2013-02-28 00:00:00
3
2013-03-31 00:00:00
3
2013-04-30 00:00:00
3
2013-05-31 00:00:00
3
2013-06-30 00:00:00
3
2013-07-31 00:00:00
3
2013-08-31 00:00:00
3
2013-09-30 00:00:00
3
2013-10-31 00:00:00
3
2013-11-30 00:00:00
3
2013-12-31 00:00:00
3
2014-01-31 00:00:00
3
2014-02-28 00:00:00
3
2014-03-31 00:00:00
3
2014-04-30 00:00:00
3
2014-05-31 00:00:00
3
2014-06-30 00:00:00
3
2014-07-31 00:00:00
3
2014-08-31 00:00:00
3
2014-09-30 00:00:00
3
2014-10-31 00:00:00
3
2014-11-30 00:00:00
3
2014-12-31 00:00:00
3
2015-01-31 00:00:00
3
2015-02-28 00:00:00
3
2015-03-31 00:00:00
3
2015-04-30 00:00:00
3
2015-05-31 00:00:00
3
2015-06-30 00:00:00
3
2015-07-31 00:00:00
3
2015-08-31 00:00:00
3
2015-09-30 00:00:00
3
2015-10-31 00:00:00
3
2015-11-30 00:00:00
3
2015-12-31 00:00:00
3
2016-01-31 00:00:00
3
2016-02-29 00:00:00
3
2016-03-31 00:00:00
3
2016-04-30 00:00:00
3
2016-05-31 00:00:00
3
2016-06-30 00:00:00
3
2016-07-31 00:00:00
3
2016-08-31 00:00:00
3
2016-09-30 00:00:00
3
2016-10-31 00:00:00
3
2016-11-30 00:00:00
3
2016-12-31 00:00:00
3
2017-01-31 00:00:00
3
2017-02-28 00:00:00
3
2017-03-31 00:00:00
3
2017-04-30 00:00:00
3
2017-05-31 00:00:00
3
2017-06-30 00:00:00
3
2017-07-31 00:00:00
3
2017-08-31 00:00:00
3
2017-09-30 00:00:00
3
2017-10-31 00:00:00
3
2017-11-30 00:00:00
3
2017-12-31 00:00:00
3
2018-01-31 00:00:00
3
2018-02-28 00:00:00
3
2018-03-31 00:00:00
3
2018-04-30 00:00:00
3
2018-05-31 00:00:00
3
2018-06-30 00:00:00
3
2018-07-31 00:00:00
3
2018-08-31 00:00:00
3
2018-09-30 00:00:00
3
2018-10-31 00:00:00
3
2018-11-30 00:00:00
3
2018-12-31 00:00:00
3
2019-01-31 00:00:00
3
2019-02-28 00:00:00
3
2019-03-31 00:00:00
3
2019-04-30 00:00:00
3
2019-05-31 00:00:00
3
2019-06-30 00:00:00
3
2019-07-31 00:00:00
3
2019-08-31 00:00:00
3
2019-09-30 00:00:00
3
2019-10-31 00:00:00
3
2019-11-30 00:00:00
3
2019-12-31 00:00:00
3
2020-01-31 00:00:00
3
2020-02-29 00:00:00
3
2020-03-31 00:00:00
3
2020-04-30 00:00:00
3
2020-05-31 00:00:00
3
2020-06-30 00:00:00
3
2020-07-31 00:00:00
3
2020-08-31 00:00:00
3
2020-09-30 00:00:00
3
2020-10-31 00:00:00
3
2020-11-30 00:00:00
3
2020-12-31 00:00:00
3
2021-01-31 00:00:00
3
2021-02-28 00:00:00
3
2021-03-31 00:00:00
3
2021-04-30 00:00:00
3
2021-05-31 00:00:00
3
2021-06-30 00:00:00
3
2021-07-31 00:00:00
3
2021-08-31 00:00:00
3
2021-09-30 00:00:00
3
2021-10-31 00:00:00
3
2021-11-30 00:00:00
3
2021-12-31 00:00:00
3
2022-01-31 00:00:00
3
2022-02-28 00:00:00
3
2022-03-31 00:00:00
3
2022-04-30 00:00:00
3
2022-05-31 00:00:00
3
2022-06-30 00:00:00
3
2022-07-31 00:00:00
3
2022-08-31 00:00:00
6
2001-01-31 00:00:00
6
2001-02-28 00:00:00
6
2001-03-31 00:00:00
6
2001-04-30 00:00:00
6
2001-05-31 00:00:00
6
2001-06-30 00:00:00
6
2001-07-31 00:00:00
6
2001-08-31 00:00:00
6
2001-09-30 00:00:00
6
2001-10-31 00:00:00
6
2001-11-30 00:00:00
6
2001-12-31 00:00:00
6
2002-01-31 00:00:00
6
2002-02-28 00:00:00
6
2002-03-31 00:00:00
6
2002-04-30 00:00:00
6
2002-05-31 00:00:00
6
2002-06-30 00:00:00
6
2002-07-31 00:00:00
6
2002-08-31 00:00:00
6
2002-09-30 00:00:00
6
2002-10-31 00:00:00
6
2002-11-30 00:00:00
6
2002-12-31 00:00:00
6
2003-01-31 00:00:00
6
2003-02-28 00:00:00
6
2003-03-31 00:00:00
6
2003-04-30 00:00:00
6
2003-05-31 00:00:00
6
2003-06-30 00:00:00
6
2003-07-31 00:00:00
6
2003-08-31 00:00:00
6
2003-09-30 00:00:00
6
2003-10-31 00:00:00
6
2003-11-30 00:00:00
6
2003-12-31 00:00:00
6
2004-01-31 00:00:00
6
2004-02-29 00:00:00
6
2004-03-31 00:00:00
6
2004-04-30 00:00:00
6
2004-05-31 00:00:00
6
2004-06-30 00:00:00
6
2004-07-31 00:00:00
6
2004-08-31 00:00:00
6
2004-09-30 00:00:00
6
2004-10-31 00:00:00
6
2004-11-30 00:00:00
6
2004-12-31 00:00:00
6
2005-01-31 00:00:00
6
2005-02-28 00:00:00
6
2005-03-31 00:00:00
6
2005-04-30 00:00:00
6
2005-05-31 00:00:00
6
2005-06-30 00:00:00
6
2005-07-31 00:00:00
6
2005-08-31 00:00:00
6
2005-09-30 00:00:00
6
2005-10-31 00:00:00
6
2005-11-30 00:00:00
6
2005-12-31 00:00:00
6
2006-01-31 00:00:00
6
2006-02-28 00:00:00
6
2006-03-31 00:00:00
6
2006-04-30 00:00:00
6
2006-05-31 00:00:00
6
2006-06-30 00:00:00
6
2006-07-31 00:00:00
6
2006-08-31 00:00:00
6
2006-09-30 00:00:00
6
2006-10-31 00:00:00
6
2006-11-30 00:00:00
6
2006-12-31 00:00:00
6
2007-01-31 00:00:00
6
2007-02-28 00:00:00
6
2007-03-31 00:00:00
6
2007-04-30 00:00:00
6
2007-05-31 00:00:00
6
2007-06-30 00:00:00
6
2007-07-31 00:00:00
6
2007-08-31 00:00:00
6
2007-09-30 00:00:00
6
2007-10-31 00:00:00
6
2007-11-30 00:00:00
6
2007-12-31 00:00:00
6
2008-01-31 00:00:00
6
2008-02-29 00:00:00
6
2008-03-31 00:00:00
6
2008-04-30 00:00:00
6
2008-05-31 00:00:00
6
2008-06-30 00:00:00
6
2008-07-31 00:00:00
6
2008-08-31 00:00:00
6
2008-09-30 00:00:00
6
2008-10-31 00:00:00
6
2008-11-30 00:00:00
6
2008-12-31 00:00:00
6
2009-01-31 00:00:00
6
2009-02-28 00:00:00
6
2009-03-31 00:00:00
6
2009-04-30 00:00:00
6
2009-05-31 00:00:00
6
2009-06-30 00:00:00
6
2009-07-31 00:00:00
6
2009-08-31 00:00:00
6
2009-09-30 00:00:00
6
2009-10-31 00:00:00
6
2009-11-30 00:00:00
6
2009-12-31 00:00:00
6
2010-01-31 00:00:00
6
2010-02-28 00:00:00
6
2010-03-31 00:00:00
6
2010-04-30 00:00:00
6
2010-05-31 00:00:00
6
2010-06-30 00:00:00
6
2010-07-31 00:00:00
6
2010-08-31 00:00:00
6
2010-09-30 00:00:00
6
2010-10-31 00:00:00
6
2010-11-30 00:00:00
6
2010-12-31 00:00:00
6
2011-01-31 00:00:00
6
2011-02-28 00:00:00
6
2011-03-31 00:00:00
6
2011-04-30 00:00:00
6
2011-05-31 00:00:00
6
2011-06-30 00:00:00
6
2011-07-31 00:00:00
6
2011-08-31 00:00:00
6
2011-09-30 00:00:00
6
2011-10-31 00:00:00
6
2011-11-30 00:00:00
6
2011-12-31 00:00:00
6
2012-01-31 00:00:00
6
2012-02-29 00:00:00
6
2012-03-31 00:00:00
6
2012-04-30 00:00:00
6
2012-05-31 00:00:00
6
2012-06-30 00:00:00
6
2012-07-31 00:00:00
6
2012-08-31 00:00:00
6
2012-09-30 00:00:00
6
2012-10-31 00:00:00
6
2012-11-30 00:00:00
6
2012-12-31 00:00:00
6
2013-01-31 00:00:00
6
2013-02-28 00:00:00
6
2013-03-31 00:00:00
6
2013-04-30 00:00:00
6
2013-05-31 00:00:00
6
2013-06-30 00:00:00
6
2013-07-31 00:00:00
6
2013-08-31 00:00:00
6
2013-09-30 00:00:00
6
2013-10-31 00:00:00
6
2013-11-30 00:00:00
6
2013-12-31 00:00:00
6
2014-01-31 00:00:00
6
2014-02-28 00:00:00
6
2014-03-31 00:00:00
6
2014-04-30 00:00:00
6
2014-05-31 00:00:00
6
2014-06-30 00:00:00
6
2014-07-31 00:00:00
6
2014-08-31 00:00:00
6
2014-09-30 00:00:00
6
2014-10-31 00:00:00
6
2014-11-30 00:00:00
6
2014-12-31 00:00:00
6
2015-01-31 00:00:00
6
2015-02-28 00:00:00
6
2015-03-31 00:00:00
6
2015-04-30 00:00:00
6
2015-05-31 00:00:00
6
2015-06-30 00:00:00
6
2015-07-31 00:00:00
6
2015-08-31 00:00:00
6
2015-09-30 00:00:00
6
2015-10-31 00:00:00
6
2015-11-30 00:00:00
6
2015-12-31 00:00:00
6
2016-01-31 00:00:00
6
2016-02-29 00:00:00
6
2016-03-31 00:00:00
6
2016-04-30 00:00:00
6
2016-05-31 00:00:00
6
2016-06-30 00:00:00
6
2016-07-31 00:00:00
6
2016-08-31 00:00:00
6
2016-09-30 00:00:00
6
2016-10-31 00:00:00
6
2016-11-30 00:00:00
6
2016-12-31 00:00:00
6
2017-01-31 00:00:00
6
2017-02-28 00:00:00
6
2017-03-31 00:00:00
6
2017-04-30 00:00:00
6
2017-05-31 00:00:00
6
2017-06-30 00:00:00
6
2017-07-31 00:00:00
6
2017-08-31 00:00:00
6
2017-09-30 00:00:00
6
2017-10-31 00:00:00
6
2017-11-30 00:00:00
6
2017-12-31 00:00:00
6
2018-01-31 00:00:00
6
2018-02-28 00:00:00
6
2018-03-31 00:00:00
6
2018-04-30 00:00:00
6
2018-05-31 00:00:00
6
2018-06-30 00:00:00
6
2018-07-31 00:00:00
6
2018-08-31 00:00:00
6
2018-09-30 00:00:00
6
2018-10-31 00:00:00
6
2018-11-30 00:00:00
6
2018-12-31 00:00:00
6
2019-01-31 00:00:00
6
2019-02-28 00:00:00
6
2019-03-31 00:00:00
6
2019-04-30 00:00:00
6
2019-05-31 00:00:00
6
2019-06-30 00:00:00
6
2019-07-31 00:00:00
6
2019-08-31 00:00:00
6
2019-09-30 00:00:00
6
2019-10-31 00:00:00
6
2019-11-30 00:00:00
6
2019-12-31 00:00:00
6
2020-01-31 00:00:00
6
2020-02-29 00:00:00
6
2020-03-31 00:00:00
6
2020-04-30 00:00:00
6
2020-05-31 00:00:00
6
2020-06-30 00:00:00
6
2020-07-31 00:00:00
6
2020-08-31 00:00:00
6
2020-09-30 00:00:00
6
2020-10-31 00:00:00
6
2020-11-30 00:00:00
6
2020-12-31 00:00:00
6
2021-01-31 00:00:00
6
2021-02-28 00:00:00
6
2021-03-31 00:00:00
6
2021-04-30 00:00:00
6
2021-05-31 00:00:00
6
2021-06-30 00:00:00
6
2021-07-31 00:00:00
6
2021-08-31 00:00:00
6
2021-09-30 00:00:00
6
2021-10-31 00:00:00
6
2021-11-30 00:00:00
6
2021-12-31 00:00:00
6
2022-01-31 00:00:00
6
2022-02-28 00:00:00
6
2022-03-31 00:00:00
6
2022-04-30 00:00:00
6
2022-05-31 00:00:00

In [32]:
mtlprice.index[12:]

DatetimeIndex(['2001-01-31', '2001-02-28', '2001-03-31', '2001-04-30',
               '2001-05-31', '2001-06-30', '2001-07-31', '2001-08-31',
               '2001-09-30', '2001-10-31',
               ...
               '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31',
               '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30',
               '2022-10-31', '2022-11-30'],
              dtype='datetime64[ns]', name='Date', length=263, freq='M')

In [33]:
mtlprice.index[12:-1]

DatetimeIndex(['2001-01-31', '2001-02-28', '2001-03-31', '2001-04-30',
               '2001-05-31', '2001-06-30', '2001-07-31', '2001-08-31',
               '2001-09-30', '2001-10-31',
               ...
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31'],
              dtype='datetime64[ns]', name='Date', length=262, freq='M')